
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-config
  namespace: default
data:
  config.yml: |
    api:
      ollama:
        host: 172.17.0.1
        port: 11434
        base_url: http://172.17.0.1:11434
        timeout: 30